# docker-compose.yaml

version: '3.8'

services:
  backend:
    # Configuration for the Flask backend service
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - "8001:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres_db

  queue:
    # Configuration for the consumer service
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'  
    depends_on:
      - postgres_db

  postgres_db:
    # Configuration for the PostgreSQL database service
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - .postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
