version: '3.8'

services:
  backend:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres_db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - .postgres_data:/var/lib/postgresql

volumes:
  postgres_data:

